#  parameter file for doing cost function minimization for optimal coating design
#
# This specifies the terms to include in your cost func
costs:
        - Trans      # Optimize for a target PSL transmission
        - coatBr     # Optimize for a target brownian noise level
        - coatTO     # Optimize for a target thermo-optic noise level
        - sensL      # Minimize sensitivity to manufacturing tolerances on optical thickness
        - surfE      # Minimize the surface E field
          #- absorp  # Minimize absorption (not yet...)
        - TransAUX   # Optimize for a target AUX transmission

# Use this to specify the target levels for each term in the cost func
# There has to be one target per term in the cost
targets:
        - 5e-6    # 5 ppm target transmission
        - 1        # chosen to match MATLAB optim
        - 1e+42   # chosen to match MATLAB optim
        - 1e-2    # NOT Used currently
        - 0       # chosen to match MATLAB optim (this seems to not be used ?)
        - 50e-6    # 50 ppm target transmission 

# Specify the relative importance of terms in the cost func
#         Trans    CoatBr    CoatTO     sensitivity   E-field    TransAUX
weights:  [10,      1e-6,      1e-9,       1,        2,        10]

# MISC
# Some other parameters that are used by the code
fTO: 100           # Hz, freq at which to evaluate TO noise
pol: te            # polarization, use "te" or "tm"
aoi: 0             # degrees, angle of incidence
Npairs: 22       # how many layer pairs; N_layers = Npairs+1
Nparticles: 100     # how many starting particles in the optimizer
gwincStructFile: 'Ta2O5Model.yml'